Make jumbler work with just 1 element to jumble
Prior to this, this would crash at runtime trying to pick an
element from an invalid range:

thread 'main' panicked at 'UniformSampler::sample_single: low >= high',
/home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/rand-0.7.3/src/distributions/uniform.rs:477:1

This isn't needed so much for production usage, but when hacking on
a specific mode, it was causing problems when commenting out all the
other modes.